spring.application.name=gateway

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

server.port=8085
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=3b0c645b-a274-4b90-9f68-df54bcef7956
